export * from "./client";
export * as schema from "./schema";

// Re-export row types + enum constants so callers can
// `import type { Property } from "@dwellverdict/db"` without reaching
// into the schema namespace.
export type {
  User,
  NewUser,
  Organization,
  NewOrganization,
  OrganizationMember,
  NewOrganizationMember,
  Property,
  NewProperty,
  PropertyStage,
  NewPropertyStage,
  PropertyType,
  PropertyStatus,
  PropertyLifecycleStage,
  OrganizationPlan,
  OrganizationMemberRole,
  Verdict,
  NewVerdict,
  VerdictSignal,
  VerdictStatus,
  UserReportUsage,
  NewUserReportUsage,
  DataSourceCacheRow,
  NewDataSourceCacheRow,
  RegulatoryCacheRow,
  NewRegulatoryCacheRow,
  RegulatoryThesisDimension,
  PlaceSentimentCacheRow,
  NewPlaceSentimentCacheRow,
  DealMilestone,
  NewDealMilestone,
  DealMilestoneType,
  DealContact,
  NewDealContact,
  DealContactRole,
  DealNote,
  NewDealNote,
  DealBudgetItem,
  NewDealBudgetItem,
  DealBudgetCategory,
  DealBudgetStatus,
  RenovationScopeItem,
  NewRenovationScopeItem,
  RenovationScopeCategory,
  RenovationScopeStatus,
  RenovationTask,
  NewRenovationTask,
  RenovationContractor,
  NewRenovationContractor,
  RenovationTrade,
  RenovationQuote,
  NewRenovationQuote,
  RenovationQuoteStatus,
  PropertyReservation,
  NewPropertyReservation,
  ReservationSource,
  ReservationStatus,
  PropertyExpense,
  NewPropertyExpense,
  ExpenseCategory,
  ScoutMessage,
  NewScoutMessage,
  AiUsageEvent,
  NewAiUsageEvent,
  AiUsageTask,
  VerdictFeedback,
  NewVerdictFeedback,
  VerdictFeedbackRating,
  VerdictFeedbackIssueCategory,
} from "./schema";

export {
  PROPERTY_TYPES,
  PROPERTY_STATUSES,
  PROPERTY_LIFECYCLE_STAGES,
  ORGANIZATION_PLANS,
  ORGANIZATION_MEMBER_ROLES,
  VERDICT_SIGNALS,
  VERDICT_STATUSES,
  DEAL_MILESTONE_TYPES,
  DEAL_CONTACT_ROLES,
  DEAL_BUDGET_CATEGORIES,
  DEAL_BUDGET_STATUSES,
  RENOVATION_SCOPE_CATEGORIES,
  RENOVATION_SCOPE_STATUSES,
  RENOVATION_TRADES,
  RENOVATION_QUOTE_STATUSES,
  RESERVATION_SOURCES,
  RESERVATION_STATUSES,
  EXPENSE_CATEGORIES,
  AI_USAGE_TASKS,
  VERDICT_FEEDBACK_RATINGS,
  VERDICT_FEEDBACK_ISSUE_CATEGORIES,
  REGULATORY_THESIS_DIMENSIONS,
} from "./schema";
